const RandomQuestion = [
  { Eng: "Describe local cuisine.", Thai: "ช่างพูดถึงอาหารท้องถิ่น" },
  { Eng: "City's iconic building?", Thai: "อาคารสำคัญของเมือง" },
  { Eng: "Any famous festivals?", Thai: "มีเทศกาลที่มีชื่อเสียงมั้ย" },
  { Eng: "Is there a nearby beach?", Thai: "มีชายหาดใกล้เคียงมั้ย" },
  { Eng: "Common local language?", Thai: "ภาษาท้องถิ่นพูดทั่วไปมั้ย" },
  { Eng: "How's the nightlife?", Thai: "ชีวิตกลางคืนเป็นอย่างไร" },
  { Eng: "Tell me about the art.", Thai: "เล่าเรื่องศิลปะท้องถิ่น" },
  { Eng: "Popular local sport?", Thai: "กีฬาที่ได้รับความนิยมในท้องถิ่น" },
  { Eng: "Main local industry?", Thai: "อุตสาหกรรมหลักคืออะไร" },
  { Eng: "Any historical sites?", Thai: "มีสถานที่ประวัติศาสตร์มั้ย" },
  { Eng: "What's the local currency?", Thai: "สกุลเงินท้องถิ่นคืออะไร" },
  { Eng: "Famous local park?", Thai: "สวนที่มีชื่อเสียงมั้ย" },
  { Eng: "Public transport here?", Thai: "ขนส่งสาธารณะเป็นอย่างไร" },
  { Eng: "Local music scene?", Thai: "ฉากเพลงท้องถิ่นมีอย่างไร" },
  { Eng: "Any must-visit markets?", Thai: "ตลาดที่ต้องไปมั้ย" },
  { Eng: "City's unique vibe?", Thai: "บรรยากาศเฉพาะของเมือง" },
  { Eng: "Famous local museums?", Thai: "พิพิธภัณฑ์ที่มีชื่อเสียงมั้ย" },
  { Eng: "Local color and culture?", Thai: "สีสันและวัฒนธรรมท้องถิ่น" },
  { Eng: "Popular local dishes?", Thai: "อาหารท้องถิ่นที่นิยม" },
  { Eng: "What's the city's history?", Thai: "ประวัติศาสตร์ของเมืองคืออะไร" },
  { Eng: "Any famous bridges?", Thai: "สะพานที่มีชื่อเสียงมั้ย" },
  { Eng: "Local traditions?", Thai: "ประเพณีท้องถิ่นมีอะไรบ้าง" },
  { Eng: "Tell me about the climate.", Thai: "บอกเกี่ยวกับสภาพอากาศที่นี่" },
  { Eng: "Is there a zoo nearby?", Thai: "มีสวนสัตว์ใกล้เคียงมั้ย" },
  { Eng: "Any famous theaters?", Thai: "โรงละครที่มีชื่อเสียงมั้ย" },
  { Eng: "Local fashion style?", Thai: "สไตล์แฟชั่นท้องถิ่น" },
  { Eng: "City's famous squares?", Thai: "สนามกว้างที่มีชื่อเสียงมั้ย" },
  { Eng: "Tell me about local art.", Thai: "เล่าเรื่องศิลปะท้องถิ่น" },
  { Eng: "Is there a famous mountain?", Thai: "มีเทือกเขาที่มีชื่อเสียงมั้ย" },
  { Eng: "Local wildlife?", Thai: "สัตว์ป่าท้องถิ่นมีอะไรบ้าง" },
  { Eng: "Any famous gardens?", Thai: "มีสวนที่มีชื่อเสียงมั้ย" },
  { Eng: "Tell me about local customs.", Thai: "เล่าเรื่องประเพณีท้องถิ่น" },
  { Eng: "Any famous lakes?", Thai: "มีทะเลสาบที่มีชื่อเสียงมั้ย" },
  { Eng: "What's the city's charm?", Thai: "เสน่ห์ของเมืองคืออะไร" },
  { Eng: "Is there a famous university?", Thai: "มีมหาวิทยาลัยที่มีชื่อเสียงมั้ย" },
  { Eng: "Any famous statues?", Thai: "มีรูปปั้นที่มีชื่อเสียงมั้ย" },
  { Eng: "Local breakfast spot?", Thai: "ที่ทานอาหารเช้าท้องถิ่น" },
  { Eng: "City's vibe during festivals?", Thai: "บรรยากาศของเมืองในช่วงเทศกาล" },
  { Eng: "Any renowned universities?", Thai: "มีมหาวิทยาลัยที่มีชื่อเสียงมั้ย" },
  { Eng: "Notable local dishes?", Thai: "อาหารท้องถิ่นที่โดดเด่น" },
  { Eng: "Tell me about local wildlife.", Thai: "เล่าเรื่องสัตว์ป่าท้องถิ่น" },
  { Eng: "Is there a famous river?", Thai: "มีแม่น้ำที่มีชื่อเสียงมั้ย" },
  { Eng: "Local art scene?", Thai: "ฉากศิลปะท้องถิ่นเป็นอย่างไร" },
  { Eng: "City's architectural style?", Thai: "สไตล์สถาปัตยกรรมของเมือง" },
  { Eng: "Any famous landmarks?", Thai: "มีสถานที่สำคัญที่มีชื่อเสียงมั้ย" },
  { Eng: "Tell me about the local dialect.", Thai: "เล่าเรื่องเครื่องหมายท้องถิ่น" },
  { Eng: "Is there a famous beach?", Thai: "มีชายหาดที่มีชื่อเสียงมั้ย" },
  { Eng: "Notable local events?", Thai: "เหตุการณ์ท้องถิ่นที่โดดเด่น" },
  { Eng: "City's popular hangout spots?", Thai: "สถานที่พักผ่อนที่ได้รับความนิยมของเมือง" },
  { Eng: "Tell me about local folklore.", Thai: "เล่าเรื่องประเพณีท้องถิ่น" },
  { Eng: "Any famous squares?", Thai: "มีสนามกว้างที่มีชื่อเสียงมั้ย" },
  { Eng: "Local market specialties?", Thai: "ของพิเศษที่ตลาดท้องถิ่น" },
  { Eng: "City's reputation?", Thai: "ชื่อเสียงของเมืองเป็นอย่างไร" },
  { Eng: "Any famous parks?", Thai: "มีสวนสาธารณะที่มีชื่อเสียงมั้ย" },
  { Eng: "Tell me about local myths.", Thai: "เล่าเรื่องนิทานท้องถิ่น" },
  { Eng: "Local means of transportation?", Thai: "บริการขนส่งท้องถิ่น" },
  { Eng: "Is there a famous market?", Thai: "มีตลาดที่มีชื่อเสียงมั้ย" },
  { Eng: "Describe the city's vibe.", Thai: "บรรยากาศของเมืองเป็นอย่างไร" },
  { Eng: "Any must-visit museums?", Thai: "มีพิพิธภัณฑ์ที่ต้องไปมั้ย" },
  { Eng: "What's the local color?", Thai: "สีสันท้องถิ่นคืออะไร" },
  { Eng: "Is there a famous park?", Thai: "มีสวนที่มีชื่อเสียงมั้ย" },
];

/*25 role*/
const HospitalRole = [
    { roleused: "Doctor", thairoleused: "<br>หมอ", roledescriptionused: "Medical professionals who diagnose and treat patients.<br><br>ผู้เชี่ยวชาญด้านการแพทย์ที่รักษาโรคและบาดเจ็บของผู้ป่วย" },
    { roleused: "Nurse", thairoleused: "<br>พยาบาล", roledescriptionused: "Healthcare professionals who provide care and support to patients.<br><br>ผู้ให้บริการดูแลและสนับสนุนผู้ป่วยทางด้านสุขภาพ" },
    { roleused: "surgeon", thairoleused: "<br>หมอผ่าตัด", roledescriptionused: "Doctors who specialize in performing surgical procedures.<br><br>หมอที่เชี่ยวชาญในการทำหัตถการ" },
    { roleused: "Radiologist", thairoleused: "<br>หมอรังสี", roledescriptionused: "Medical professionals who interpret medical images, such as X-rays.<br><br>ผู้เชี่ยวชาญด้านการตีความรูปภาพทางการแพทย์ เช่น รังสี-X" },
    { roleused: "Pharmacist", thairoleused: "<br>เภสัชกร", roledescriptionused: "Healthcare professionals who dispense medication and provide pharmaceutical care.<br><br>ผู้ให้บริการด้านยาและการดูแลทางเภสัชกรรม" },
    { roleused: "Patient", thairoleused: "<br>ผู้ป่วย", roledescriptionused: "Individuals receiving medical care and treatment in the hospital.<br><br>บุคคลที่ได้รับการดูแลและรักษาทางการแพทย์ในโรงพยาบาล" },
    { roleused: "Psychiatric Patient", thairoleused: "<br>ผู้ป่วยจิตเวช", roledescriptionused: "Individuals receiving treatment for mental health conditions in the hospital.<br><br>บุคคลที่ได้รับการรักษาสำหรับสุขภาพจิตในโรงพยาบาล" },
    { roleused: "Disabled Person", thairoleused: "<br>คนพิการ", roledescriptionused: "Individuals with physical or cognitive disabilities within the hospital.<br><br>บุคคลที่มีความพิการทางร่างกายหรือสติปัญญาในโรงพยาบาล" },
    { roleused: "Hospital Corpse", thairoleused: "<br>ศพในโรงพยาบาล", roledescriptionused: "Deceased individuals within the hospital setting.<br><br>บุคคลที่เสียชีวิตในบริเวณโรงพยาบาล" },
    { roleused: "Administrator", thairoleused: "<br>ผู้ดูแลระบบ", roledescriptionused: "Individuals responsible for managing and overseeing hospital operations.<br><br>บุคคลที่รับผิดชอบในการจัดการและดูแลการดำเนินงานของโรงพยาบาล" },
    { roleused: "Paramedic", thairoleused: "<br>พยาบาลกู้ชีวิต", roledescriptionused: "Emergency medical professionals who provide pre-hospital care.<br><br>บุคลากรทางการแพทย์ฉุกเฉินที่ให้บริการดูแลก่อนถึงโรงพยาบาล" },
    { roleused: "Lab Technician", thairoleused: "<br>ช่างทดสอบทางห้องปฏิบัติการ", roledescriptionused: "Professionals who conduct tests on clinical specimens in the laboratory.<br><br>ผู้เชี่ยวชาญที่ทดสอบตัวอย่างทางคลินิกในห้องปฏิบัติการ" },
    { roleused: "Physical Therapist", thairoleused: "<br>นักกายภาพบำบัด", roledescriptionused: "Healthcare professionals who assist patients in recovering physical abilities.<br><br>ผู้ให้บริการด้านสุขภาพที่ช่วยเหลือผู้ป่วยในการฟื้นฟูความสามารถทางกาย" },
    { roleused: "Security Guard", thairoleused: "<br>พนักงานรักษาความปลอดภัย", roledescriptionused: "Personnel responsible for maintaining a secure and safe hospital environment.<br><br>บุคลากรที่รับผิดชอบในการรักษาสภาพแวดล้อมที่ปลอดภัยในโรงพยาบาล" },
    { roleused: "Psychiatrist", thairoleused: "<br>จิตแพทย์", roledescriptionused: "Medical professionals specializing in the diagnosis and treatment of mental health disorders.<br><br>ผู้เชี่ยวชาญด้านการวินิจฉัยและรักษาสุขภาพจิต" },
    { roleused: "Social Worker", thairoleused: "<br>นักสังคมสงเคราะห์", roledescriptionused: "Professionals who provide social support and assistance to patients and their families.<br><br>ผู้ให้บริการด้านสังคมสงเคราะห์ที่ให้การสนับสนุนและความช่วยเหลือแก่ผู้ป่วยและครอบครัว" },
    { roleused: "Dietitian", thairoleused: "<br>โภชนากร", roledescriptionused: "Healthcare professionals specializing in nutrition and dietary planning.<br><br>ผู้เชี่ยวชาญด้านโภชนาการและการวางแผนอาหาร" },
    { roleused: "Janitor", thairoleused: "<br>พนักงานทำความสะอาด", roledescriptionused: "Personnel responsible for cleaning and maintaining the hospital facilities.<br><br>บุคลากรที่รับผิดชอบในการทำความสะอาดและดูแลสถานที่ในโรงพยาบาล" },
    { roleused: "Medical Student", thairoleused: "<br>นักศึกษาแพทย์", roledescriptionused: "Individuals currently studying medicine and gaining practical experience in the hospital.<br><br>บุคคลที่กำลังศึกษาการแพทย์และได้รับประสบการณ์ทางปฏิบัติในโรงพยาบาล" },
    { roleused: "Hospital Chaplain", thairoleused: "<br>นักบวชโรงพยาบาล", roledescriptionused: "spiritual and religious leaders who provide emotional and spiritual support to patients.<br><br>ผู้นำทางศาสนาและธรรมะที่ให้การสนับสนุนทางอารมณ์และทางจิตวิญญาณแก่ผู้ป่วย" },
    { roleused: "Bioethicist", thairoleused: "<br>นักวิจจัยทางชีวภาพ", roledescriptionused: "Professionals who address ethical issues related to healthcare and medical research.<br><br>ผู้เชี่ยวชาญที่ต้องการปรับปรุงต่อจริยธรรมที่เกี่ยวข้องกับด้านสุขภาพและการวิจัยทางการแพทย์" },
    { roleused: "Hospital Volunteer", thairoleused: "<br>อาสาสมัครในโรงพยาบาล", roledescriptionused: "Individuals who offer their time and services to assist patients and hospital staff.<br><br>บุคคลที่ให้เวลาและบริการเพื่อช่วยเหลือผู้ป่วยและบุคลากรในโรงพยาบาล" },
    { roleused: "Hospital Chef", thairoleused: "<br>พ่อครัวโรงพยาบาล", roledescriptionused: "Culinary professionals responsible for preparing nutritious meals for patients.<br><br>บุคลากรที่รับผิดชอบในการเตรียมอาหารที่อุดมไปด้วยสารอาหารสำหรับผู้ป่วย" },
    { roleused: "Hospital Clown", thairoleused: "<br>ตัวตลกโรงพยาบาล", roledescriptionused: "Entertainers who bring joy and laughter to patients through performances.<br><br>นักแสดงบันเทิงที่นำความรื่นเริงและการหัวเราะให้แก่ผู้ป่วยผ่านการแสดง" },
    { roleused: "Hospital Reception", thairoleused: "<br>แผนกต้อนรับโรงพยาบาล", roledescriptionused: "Individual responsible for managing the front desk and assisting visitors at the hospital.<br><br>บุคลากรที่รับผิดชอบในการจัดการเคาน์เตอร์บริการลูกค้าและช่วยเหลือผู้เยี่ยมชมในโรงพยาบาล" },
  ];
  
/*25 role*/
  const SchoolRole = [
    { roleused: "Principal", thairoleused: "<br>ผู้อำนวยการ", roledescriptionused: "The head administrator of the school responsible for overseeing its operations.<br><br>ผู้บริหารสูงสุดของโรงเรียนที่รับผิดชอบในการดูแลการดำเนินงาน" },
    { roleused: "Student", thairoleused: "<br>นักเรียน", roledescriptionused: "Individuals attending classes and receiving education in the school.<br><br>บุคคลที่เข้าร่วมการเรียนการสอนและได้รับการศึกษาในโรงเรียน" },
    { roleused: "Nerd", thairoleused: "<br>เนิร์ด", roledescriptionused: "An academically focused student with a passion for learning and a vast knowledge in various subjects.<br><br>นักเรียนที่ให้ความสำคัญกับด้านทางวิชาการ มีความหลงใหลในการเรียนรู้และมีความรู้ที่แน่นอนในหลายวิชา" },
    { roleused: "Rascal", thairoleused: "<br>นักเลง", roledescriptionused: "A mischievous student who enjoys playing pranks and creating a lively atmosphere in school.<br><br>นักเรียนที่ชอบทำน้องร้ายและสร้างบรรยากาศร่าเริงในโรงเรียน" },
    { roleused: "Librarian", thairoleused: "<br>บรรณารักษ์", roledescriptionused: "Personnel responsible for managing the school library and assisting students with resources.<br><br>บุคลากรที่รับผิดชอบในการจัดการห้องสมุดของโรงเรียนและช่วยเหลือนักเรียนในการใช้ทรัพยากร" },
    { roleused: "Janitor", thairoleused: "<br>พนักงานทำความสะอาด", roledescriptionused: "Personnel responsible for cleaning and maintaining the school facilities.<br><br>บุคลากรที่รับผิดชอบในการทำความสะอาดและบำรุงรักษาสิ่งอำนวยความสะดวกของโรงเรียน" },
    { roleused: "School Guard", thairoleused: "<br>พนักงานรักษาความปลอดภัย", roledescriptionused: "Personnel responsible for ensuring the safety and security of the school premises.<br><br>บุคลากรที่รับผิดชอบในการรักษาความปลอดภัยและความปลอดภัยในที่ตั้งของโรงเรียน" },
    { roleused: "Cafeteria Cooker", thairoleused: "<br>พ่อครัวโรงอาหาร", roledescriptionused: "Person responsible for preparing and cooking delicious meals for students and staff in the school cafeteria.<br><br>บุคลากรที่รับผิดชอบในการเตรียมและทำอาหารอร่อยสำหรับนักเรียนและบุคลากรในโรงอาหารของโรงเรียน" },
    { roleused: "Bus Driver", thairoleused: "<br>คนขับรถโรงเรียน", roledescriptionused: "Individual responsible for safely transporting students to and from the school.<br><br>บุคคลที่รับผิดชอบในการขนส่งนักเรียนไป-กลับจากโรงเรียนอย่างปลอดภัย" },
    { roleused: "Student Council President", thairoleused: "<br>ประธานสภานักเรียน", roledescriptionused: "Elected student leader responsible for representing the student body.<br><br>ผู้นำนักเรียนที่เลือกตั้งที่รับผิดชอบในการแทนร่างนักเรียน" },
    { roleused: "School Photographer", thairoleused: "<br>ช่างภาพโรงเรียน", roledescriptionused: "Individual responsible for capturing and documenting school events through photography.<br><br>บุคคลที่รับผิดชอบในการถ่ายภาพและเก็บรวบรวมเหตุการณ์ในโรงเรียนผ่านทางภาพถ่าย" },
    { roleused: "School Nurse", thairoleused: "<br>ครูพยาบาล", roledescriptionused: "Healthcare professional responsible for providing medical care to students and staff.<br><br>ผู้ให้บริการด้านสุขภาพที่รับผิดชอบในการให้บริการการดูแลทางการแพทย์ให้แก่นักเรียนและบุคลากร" },
    { roleused: "Computer Sci. Teacher", thairoleused: "<br>ครูวิทยาการคอมพิวเตอร์", roledescriptionused: "Educator specializing in teaching students computer science and programming.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนนักเรียนวิทยาการคอมพิวเตอร์และโปรแกรมมิ่ง" },
    { roleused: "Music Teacher", thairoleused: "<br>ครูดนตรี", roledescriptionused: "Educator specializing in teaching students music and musical instruments.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนนักเรียนดนตรีและเครื่องดนตรี" },
    { roleused: "Art Teacher", thairoleused: "<br>ครูศิลปะ", roledescriptionused: "Educator specializing in teaching students various forms of art.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนนักเรียนทางศิลปะต่าง ๆ" },
    { roleused: "Foreign Teacher", thairoleused: "<br>ครูภาษาต่างประเทศ", roledescriptionused: "Educator specializing in teaching students languages other than their native language.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนภาษาที่ไม่ใช่ภาษาเกิด" },
    { roleused: "Physics Teacher", thairoleused: "<br>ครูฟิสิกส์", roledescriptionused: "Educator specializing in teaching students the principles of physics.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนนักเรียนหลักการของฟิสิกส์" },
    { roleused: "Chemistry Teacher", thairoleused: "<br>ครูเคมี", roledescriptionused: "An educator specializing in teaching students the principles and applications of chemistry.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนหลักการและการประยุกต์ของเคมี" },
    { roleused: "Biology Teacher", thairoleused: "<br>ครูชีววิทยา", roledescriptionused: "An educator specializing in teaching students the principles and intricacies of biology.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนหลักการและความซับซ้อนของชีววิทยา" },
    { roleused: "PE Teacher", thairoleused: "<br>ครูพละ", roledescriptionused: "An educator specializing in teaching physical education and promoting a healthy and active lifestyle.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนพละและส่งเสริมวิถีชีวิตที่สุขภาพและมีกิจกรรม" },
    { roleused: "Math Teacher", thairoleused: "<br>ครูคณิตศาสตร์", roledescriptionused: "An educator specializing in teaching students the principles and applications of mathematics.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนหลักการและการประยุกต์ของคณิตศาสตร์" },
    { roleused: "History Teacher", thairoleused: "<br>ครูประวัติศาสตร์", roledescriptionused: "An educator specializing in teaching students about historical events, cultures, and civilizations.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนเหตุการณ์ทางประวัติศาสตร์ วัฒนธรรม และสังคมของมนุษย์" },
    { roleused: "Economy Teacher", thairoleused: "<br>ครูเศรษฐศาสตร์", roledescriptionused: "An educator specializing in teaching students the principles and concepts of economics.<br><br>ผู้สอนที่เชี่ยวชาญในการสอนหลักการและแนวคิดของเศรษฐศาสตร์" },
    { roleused: "Guidance Teacher", thairoleused: "<br>ครูแนะแนว", roledescriptionused: "An educator responsible for providing guidance and support to students in matters related to personal development and academic choices.<br><br>ผู้สอนที่รับผิดชอบในการให้คำแนะนำและสนับสนุนนักเรียนในเรื่องที่เกี่ยวข้องกับการพัฒนาตนเองและการเลือกทางการเรียน" },
    { roleused: "School Footballer", thairoleused: "<br>นักบอลโรงเรียน", roledescriptionused: "A skilled football player representing the school in various competitions and sports events.<br><br>นักเรียนที่เชี่ยวชาญในการเล่นฟุตบอลและแทนโรงเรียนในการแข่งขันและกิจกรรมกีฬาต่าง ๆ" },
];                         

/*25 role*/
const SpaceStationRole = [
    {roleused: "Astronaut Captain", thairoleused: "<br>นักบินอวกาศกัปตัน", roledescriptionused: "The leader of the space station crew, responsible for overseeing operations and ensuring the crew safety.<br><br>ผู้นำของลูกเรืออวกาศที่รับผิดชอบในการดูแลการดำเนินงานและรักษาความปลอดภัยของลูกเรือ" },
    {roleused: "Astronaut", thairoleused: "<br>นักบินอวกาศ", roledescriptionused: "Individuals trained to travel into space and perform various activities there.<br><br>ผู้ที่ได้รับการฝึกอบรมเพื่อเดินทางไปยังอวกาศเพื่อดำเนินกิจกรรมต่าง ๆ ในอวกาศ"},
    {roleused: "Mission Commander", thairoleused: "<br>ผู้บังคับการภารกิจ", roledescriptionused: "Responsible for leading and overseeing space missions.<br><br>ผิดชอบในการนำและกำกับภารกิจอวกาศ"},
    {roleused: "Alien", thairoleused: "<br>เอเลี่ยน", roledescriptionused: "Extraterrestrial life forms from outside Earth.<br><br>สิ่งมีชีวิตนอกโลก"},
    {roleused: "Astrobiologist", thairoleused: "<br>นักชีวศาสตร์อวกาศ", roledescriptionused: "scientists who study extraterrestrial life and environments on other celestial bodies.<br><br>ศึกษาชีวิตนอกโลกและสภาวะสภาพแวดล้อมที่สว่างอย่างอุดมสมบูรณ์บนดาวอื่น ๆ"},
    {roleused: "Space Scientist", thairoleused: "<br>นักวิทยาศาสตร์อวกาศ", roledescriptionused: "Researchers who study space-related phenomena and celestial bodies. วิจัยและทดลองทางดาราศาสตร์ที่เกี่ยวข้องกับอวกาศและสวรรค์ทางดาราศาสตร์อื่น ๆ"},
    {roleused: "Payload Specialist", thairoleused: "<br>นักวิชาการเครื่องบรรจุ", roledescriptionused: "Professionals responsible for managing and operating scientific experiments and equipment on spacecraft.<br><br>รับผิดชอบการจัดการและการทำงานกับการทดลองและอุปกรณ์วิทยาศาสตร์บนยานอวกาศ"},
    {roleused: "Communicationist", thairoleused: "<br>เจ้าหน้าที่สื่อสาร", roledescriptionused: "Responsible for maintaining and controlling communications during space missions. รับผิดชอบในการรักษาสื่อสารและควบคุมการสื่อสารในภารกิจอวกาศ"},
    {roleused: "Mission Operator", thairoleused: "<br>ผู้ควบคุมการภารกิจ", roledescriptionused: "Responsible for managing various operations during space missions.<br><br>รับผิดชอบในการดำเนินการต่าง ๆ ในภารกิจอวกาศ"},
    {roleused: "Medical Officer", thairoleused: "<br>เจ้าหน้าที่แพทย์", roledescriptionused: "Professionals responsible for the health and well-being of astronauts and mission personnel.<br><br>รับผิดชอบดูแลสุขภาพของนักบินและภารกิจ"},
    {roleused: "Biomedical Scientist", thairoleused: "<br>นักวิทยาศาสตร์ชีวแพทย์", roledescriptionused: " Scientists specializing in medical and health-related research in space and celestial environments.<br><br>ศึกษาการแพทย์และสุขภาพในอวกาศและสวรรค์"},
    {roleused: "Astrophysicist", thairoleused: "<br>นักฟิสิกส์ดาราศาสตร์", roledescriptionused: "scientists who study astrophysics, the physics of celestial bodies and the universe.<br><br>ศึกษาดาราศาสตร์และกฎกลึงทางฟิสิกส์ที่มีผลต่ออวกาศและวิวัฒนาการของดวงดาว"},
    {roleused: "space Engineer", thairoleused: "<br>วิศวกรอวกาศ", roledescriptionused: "Engineers who design and build spacecraft and related equipment.<br><br>ออกแบบและสร้างอุปกรณ์และยานอวกาศ"},
    {roleused: "Navigator", thairoleused: "<br>ผู้นำทาง", roledescriptionused: "Person responsible for charting courses and ensuring the correct navigation of the space station.<br><br>บุคคลที่รับผิดชอบในการกำหนดเส้นทางและให้การนำทางที่ถูกต้องในจักรวาลอวกาศ" },    
    {roleused: "Space Psychologist", thairoleused: "<br>นักจิตวิทยาอวกาศ", roledescriptionused: "Cares for astronauts mental health.<br><br>ศึกษาสุขภาพจิตของนักบินในอวกาศ"},
    {roleused: "Supply Officer", thairoleused: "<br>เจ้าหน้าที่คลังของ", roledescriptionused: "Manages mission supplies and equipment.<br><br>จัดหาพัสดุในอวกาศเพื่อรองรับภารกิจ"},
    {roleused: "Astrogeologist", thairoleused: "<br>นักธรณีวิทยาดาราศาสตร์", roledescriptionused: "studies celestial bodies geology. ศึกษาสภาพธรณีวิทยาของดวงดาวและสวรรค์"},
    {roleused: "Flight Surgeon", thairoleused: "<br>แพทย์ดูแลอวกาศ", roledescriptionused: "Monitors astronaut health in space.<br><br>ดูแลสุขภาพของนักบินในอวกาศและบริเวณด้วย"},
    {roleused: "Zero-G Trainer", thairoleused: "<br>ครูฝึกไร้แรงโนมถ่วง", roledescriptionused: "Trainer responsible for preparing the crew for zero-gravity experiences and emergencies.<br><br>ผู้ฝึกที่รับผิดชอบในการเตรียมความพร้อมของลูกนักท่องเที่ยวสำหรับประสบการณ์ที่ไม่มีแรงโน้มถ่วงและสถานการณ์ฉุกเฉิน"},
    {roleused: "Exobiologist", thairoleused: "<br>นักชีววิทยาต่างดาว", roledescriptionused: "scientist studying potential extraterrestrial life forms and their adaptation to space environments.<br><br>นักวิทยาศาสตร์ที่ศึกษารูปแบบชีวิตต่างดาวที่เป็นไปได้และการปรับตัวของมันในสภาพแวดล้อมทางอวกาศ" },
    {roleused: "Astrophysicist", thairoleused: "<br>นักฟิสิกส์ดาราศาสตร์", roledescriptionused: "scientist studying the physical properties and behavior of celestial bodies, including stars, planets, and galaxies.<br><br>นักวิทยาศาสตร์ที่ศึกษาคุณสมบัติทางฟิสิกส์และพฤติกรรมของวัตถุทางท้องฟ้า รวมถึงดาว ดาวเคราะห์ และดาราศาสตร์" },
    {roleused: "Space Explorer", thairoleused: "<br>นักสำรวจอวกาศ", roledescriptionused: "Adventurous individual tasked with exploring uncharted territories and discovering new phenomena in the vastness of space.<br><br>บุคคลผจญภัยที่มีหน้าที่สำรวจดินแดนที่ไม่เคยได้สำรวจและค้นพบปรากฎการณ์ใหม่ในอวกาศที่อวดเสียง"},
    {roleused: "Satellite Engineer", thairoleused: "<br>วิศวกรดาวเทียม", roledescriptionused: "specialist in designing, constructing, and maintaining communication and observation satellites in Earth orbit.<br><br>ผู้เชี่ยวชาญในการออกแบบ ก่อสร้าง และบำรุงรักษาดาวเทียมทางสื่อสารและดาวเทียมทางการสังเกตการณ์ในวงโคจรโลก" },
    {roleused: "Exo-Geologist", thairoleused: "<br>นักธรณีวิทยานอกโลก", roledescriptionused: "scientist specializing in studying the geological features and composition of extraterrestrial bodies beyond Earth.<br><br>นักวิทยาศาสตร์ที่เชี่ยวชาญในการศึกษาลักษณะธรณีวิทยาและส่วนประกอบของวัตถุนอกโลก" },
    {roleused: "Quantum Physicist", thairoleused: "<br>นักฟิสิกส์ควอนตัม", roledescriptionused: "scientist specializing in the study of quantum mechanics, exploring the fundamental principles of subatomic particles and their behavior in space.<br><br>นักวิทยาศาสตร์ที่เชี่ยวชาญในการศึกษาเรื่องกฎหมายของควอนตัม การสำรวจหลักการพื้นฐานของอนุภาคซับอะตอมและพฤติกรรมของมันในอวกาศ" },
];

/*25 role*/
const BankRole = [
    {roleused: "Bank Teller", thairoleused: "<br>พนักงานสาขาธนาคาร", roledescriptionused: "Responsible for assisting bank customers with their financial transactions.<br><br>รับผิดชอบในการช่วยลูกค้าธนาคารในการทำธุรกรรมทางการเงินของพวกเขา"},
    {roleused: "Loan Officer", thairoleused: "<br>เจ้าหน้าที่อนุมัติสินเชื่อ", roledescriptionused: "Evaluates and approves loan applications for individuals and businesses.<br><br>ประเมินและอนุมัติการสมัครสินเชื่อสำหรับบุคคลและธุรกิจ"},
    {roleused: "Bank Manager", thairoleused: "<br>ผู้จัดการธนาคาร", roledescriptionused: "Manages the daily operations of a bank branch.<br><br>จัดการกับการดำเนินงานประจำวันของสาขาธนาคาร"},
    {roleused: "Financial Advisor", thairoleused: "<br>ที่ปรึกษาทางการเงิน", roledescriptionused: "Provides financial advice and investment recommendations to clients.<br><br>ให้คำแนะนำทางการเงินและข้อเสนอแนะในการลงทุนแก่ลูกค้า"},
    {roleused: "Credit Analyst", thairoleused: "<br>นักวิเคราะห์เครดิต", roledescriptionused: "Analyzes the creditworthiness of individuals and businesses.<br><br>วิเคราะห์ความคุ้มครองในการให้สินเชื่อแก่บุคคลและธุรกิจ"},
    {roleused: "Bank Auditor", thairoleused: "<br>ผู้ตรวจสอบธนาคาร", roledescriptionused: "Conducts internal audits to ensure compliance and financial accuracy.<br><br>ดำเนินการตรวจสอบภายในเพื่อให้มั่นใจในการปฏิบัติตามกฏระเบียบและความถูกต้องทางการเงิน"},
    {roleused: "Investment Banker", thairoleused: "<br>นักลงทุนธนาคาร", roledescriptionused: "Manages financial transactions for corporate clients and offers investment advice.<br><br>จัดการธุรกรรมทางการเงินสำหรับลูกค้าบริษัทและให้คำแนะนำในการลงทุน"},
    {roleused: "Mortgage Broker", thairoleused: "<br>โบรกเกอร์สินเชื่อบ้าน", roledescriptionused: "Helps individuals find and secure mortgage loans.<br><br>ช่วยให้บุคคลค้นหาและรับสินเชื่อจดจำนอง"},
    {roleused: "Financial Analyst", thairoleused: "<br>นักวิเคราะห์การเงิน", roledescriptionused: "Analyzes financial data and provides insights for investment decisions.<br><br>วิเคราะห์ข้อมูลการเงินและให้ข้อมูลเชิงลึกสำหรับการตัดสินใจในการลงทุน"},
    {roleused: "security Guard", thairoleused: "<br>ยาม", roledescriptionused: "Ensures the safety and security of a bank premises and customers.<br><br>รักษาความปลอดภัยและความมั่นคงของที่ตั้งและลูกค้าของธนาคาร"},
    {roleused: "Treasury Analyst", thairoleused: "<br>นักวิเคราะห์สินทรัพย์", roledescriptionused: "Manages a company financial assets and cash flow.<br><br>จัดการทรัพยากรการเงินและกระแสเงินสดของบริษัท"},
    {roleused: "Commercial Banker", thairoleused: "<br>นักธุรกิจธนาคาร", roledescriptionused: "Provides financial services and loans to businesses.<br><br>ให้บริการทางการเงินและสินเชื่อแก่ธุรกิจ"},
    {roleused: "Financial Planner", thairoleused: "<br>นักวางแผนการเงิน", roledescriptionused: "Helps individuals and businesses create financial plans and achieve financial goals.<br><br>ช่วยให้บุคคลและธุรกิจสร้างแผนการเงินและบรรลุเป้าหมายทางการเงิน"},
    {roleused: "Credit Manager", thairoleused: "<br>ผู้จัดการแผนกเครดิต", roledescriptionused: "Manages a company credit policies and evaluates credit risks.<br><br>จัดการนโยบายเครดิตของบริษัทและประเมินความเสี่ยงทางเครดิต"},
    {roleused: "Depositor", thairoleused: "<br>ผู้ฝากเงิน", roledescriptionused: "Individuals or businesses that deposit money into a bank.<br><br>บุคคลหรือธุรกิจที่ฝากเงินในธนาคาร"},
    {roleused: "Branch Administrator", thairoleused: "<br>ผู้ดูแลสาขา", roledescriptionused: "Responsible for administrative tasks within a bank branch.<br><br>รับผิดชอบงานด้านการบริหารที่สาขาธนาคาร"},
    {roleused: "Investment Analyst", thairoleused: "<br>นักวิเคราะห์การลงทุน", roledescriptionused: "Analyzes investments and provides recommendations for portfolio management.<br><br>วิเคราะห์การลงทุนและให้ข้อเสนอแนะในการบริหารพอร์ตการลงทุน"},
    {roleused: "Millionaire", thairoleused: "<br>เศรษฐี", roledescriptionused: "A person with a net worth of one million or more.<br><br>บุคคลที่มีสุทธินิยมเป็นหนึ่งล้านหรือมากกว่า"},
    {roleused: "Risk Analyst", thairoleused: "<br>นักวิเคราะห์ความเสี่ยง", roledescriptionused: "Assesses and manages risks associated with financial activities.<br><br>ประเมินและจัดการความเสี่ยงที่เกี่ยวข้องกับกิจกรรมทางการเงิน"},
    {roleused: "Financial Controller", thairoleused: "<br>ผู้ควบคุมการเงิน", roledescriptionused: "Oversees a company financial operations and reporting.<br><br>ควบคุมกิจกรรมทางการเงินและรายงานของบริษัท"},
    {roleused: "Bank Robber", thairoleused: "<br>โจรปล้นธนาคาร", roledescriptionused: "Criminal mastermind planning and executing a daring bank heist, attempting to make a successful getaway with the loot.<br><br>อาชญากรที่วางแผนและดำเนินการปล้นธนาคารอย่างกล้าหาญเพื่อพยายามทำการหลบหนีอย่างประสบความสำเร็จพร้อมกับทรัพย์สินที่ปล้นไป"},
    {roleused: "Scammer", thairoleused: "<br>นักต้มตุ๋น", roledescriptionused: "Deceptive individual attempting to defraud bank customers through various schemes and fraudulent activities.<br><br>บุคคลที่หลอกลวงพยายามที่จะทำให้ลูกค้าของธนาคารเสียหายผ่านทางวางแผนและกิจกรรมที่หลอกลวง" },
    {roleused: "Bank Borrower", thairoleused: "<br>ผู้กู้ยืมเงินจากธนาคาร", roledescriptionused: "Individual who has taken a loan from the bank for various purposes, such as purchasing a home or funding a business.<br><br>บุคคลที่ขอยืมเงินจากธนาคารเพื่อวัตถุประสงค์ต่าง ๆ เช่น การซื้อบ้านหรือการให้ทุนในธุรกิจ" },
    {roleused: "Businessman", thairoleused: "<br>นักธุรกิจ", roledescriptionused: "Entrepreneur engaged in various business activities, making strategic decisions to achieve success and financial growth.<br><br>ผู้ประกอบการที่มีส่วนร่วมในกิจกรรมทางธุรกิจต่าง ๆ ทำการตัดสินใจทางกลยุทธ์เพื่อบรรลุความสำเร็จและการเติบโตทางการเงิน" },
    {roleused: "Bank Janitor", thairoleused: "<br>พนักงานทำความสะอาด", roledescriptionused: "Diligent staff responsible for maintaining cleanliness and hygiene within the bank premises.<br><br>บุคลากรที่รับผิดชอบในการรักษาความสะอาดและอนามัยภายในพื้นที่ของธนาคาร" },
];

/*25 role*/
const SupermarketRole = [
    {roleused: "Store Manager", thairoleused: "<br>ผู้จัดการร้านสุขภัณฑ์", roledescriptionused: "store Managers oversee daily store operations.<br><br>ผู้จัดการร้านค้าควบคุมการดำเนินงานประจำวันของร้าน"},
    {roleused: "Service Manager", thairoleused: "<br>ผู้จัดการบริการลูกค้า", roledescriptionused: "service Managers manage customer service.<br><br>ผู้จัดการบริการจัดการบริการลูกค้า"},
    {roleused: "Grocery Manager", thairoleused: "<br>ผู้จัดการแผนกซื้อของชำ", roledescriptionused: "Grocery Managers oversee grocery departments.<br><br>ผู้จัดการซุปเปอร์มาร์เก็ตควบคุมแผนกของซุปเปอร์มาร์เก็ต"},
    {roleused: "Cashier", thairoleused: "<br>พนักงานเก็บเงิน", roledescriptionused: "Cashiers handle customer payments at checkout.<br><br>พนักงานรับเงินจ่ายเงินให้กับลูกค้าที่จุดจ่ายเงิน"},
    {roleused: "Customer Service", thairoleused: "<br>ตัวแทนบริการลูกค้า", roledescriptionused: "Customer Service assists and supports customers.<br><br>บริการลูกค้าให้ความช่วยเหลือและสนับสนุนลูกค้า"},
    {roleused: "Stock Clerk", thairoleused: "<br>พนักงานเก็บรายการสินค้า", roledescriptionused: "stock Clerks manage inventory and restocking.<br><br>พนักงานจัดเก็บคลังสินค้าจัดการสินค้าในคลังและการเติมสินค้า"},
    {roleused: "Deli Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์ของสด", roledescriptionused: "Deli Workers prepare and serve deli items.<br><br>พนักงานร้านอาหารที่เตรียมและเสิร์ฟอาหารอาหารบริเวณร้านอาหาร"},
    {roleused: "Bakery Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์เบเกอรี่", roledescriptionused: "Bakery Staff work in the bakery department.<br><br>พนักงานขนมปังทำงานในแผนกขนมปัง"},
    {roleused: "Butcher Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์เนื้อสัตว์", roledescriptionused: "Butchers prepare and sell meat products.<br><br>พ่อครัวเตรียมและขายผลิตภัณฑ์เนื้อสัตว์"},
    {roleused: "Store Cleaner", thairoleused: "<br>พนักงานทำความสะอาดร้าน", roledescriptionused: "store Cleaners maintain store cleanliness.<br><br>พนักงานทำความสะอาดร้านค้ารักษาร้านค้าให้สะอาด"},
    {roleused: "Shelf Clerk", thairoleused: "<br>พนักงานเตรียมสินค้าใส่ชั้น", roledescriptionused: "shelf Stockers replenish product shelves.<br><br>พนักงานเติมสินค้าลงบนชั้น"},
    {roleused: "Security Guard", thairoleused: "<br>ยาม", roledescriptionused: "security Guards ensure store security.<br><br>พนักงานรักษาความปลอดภัยในร้านค้า"},
    {roleused: "Dairy Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์นม", roledescriptionused: "Dairy Clerks handle dairy products.<br><br>พนักงานแผนกนมดูแลสินค้านม"},
    {roleused: "Frozen Food Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์อาหารแช่แข็ง", roledescriptionused: "Employee responsible for assisting customers with frozen food products and maintaining the frozen foods section.<br><br>พนักงานที่รับผิดชอบในการช่วยเหลือลูกค้าด้านผลิตภัณฑ์อาหารแช่แข็งและรักษาส่วนของสินค้าแช่แข็ง" },
    {roleused: "Pet Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์สัตว์เลี้ยง", roledescriptionused: "Employee specialized in assisting pet owners in selecting the right food products for their pets.<br><br>พนักงานที่เชี่ยวชาญในการช่วยเหลือเจ้าของสัตว์เลี้ยงในการเลือกผลิตภัณฑ์อาหารที่เหมาะสมสำหรับสัตว์เลี้ยงของพวกเขา" },
    {roleused: "Children's Items Clerk", thairoleused: "<br>พนักงานผลิตภัณฑ์ของใช้เด็ก", roledescriptionused: "Employee specializing in assisting parents in selecting and finding items suitable for children.<br><br>พนักงานที่เชี่ยวชาญในการช่วยเหลือพ่อแม่ในการเลือกและค้นหาของใช้ที่เหมาะสมสำหรับเด็ก" },
    {roleused: "Cart Collector", thairoleused: "<br>พนักงานเก็บรถเข็น", roledescriptionused: "Employee responsible for collecting and organizing shopping carts in the supermarket.<br><br>พนักงานที่รับผิดชอบในการเก็บรถเข็นที่ลูกค้าใช้ในซุปเปอร์มาร์เก็ต"},
    {roleused: "Store Greeter", thairoleused: "<br>พนักงานต้อนรับลูกค้า", roledescriptionused: "store Greeters welcome customers.<br><br>พนักงานต้อนรับลูกค้าในร้านค้า"},
    {roleused: "Supermarket Dog", thairoleused: "<br>หมาหน้าร้านค้า", roledescriptionused: "supermarket Dogs are friendly in front stores.<br><br>หมาหน้าร้านค้าเพื่อความเป็นมิตรในร้านค้า"},
    {roleused: "Customer", thairoleused: "<br>ลูกค้า", roledescriptionused: "Customers shop and purchase items.<br><br>ลูกค้าเข้ามาช้อปปิ้งและซื้อสินค้า"},
    {roleused: "Karen", thairoleused: "<br>มนุษย์ป้า", roledescriptionused: "Stereotypical customer known for exhibiting entitled or demanding behavior, often seeking to speak with the manager.<br><br>ลูกค้าที่มีลักษณะภาพที่เผยแพร่ที่มีประสิทธิภาพหรือทักท้วงที่จะพูดคุยกับผู้จัดการ" },
    {roleused: "Shoplifter", thairoleused: "<br>โจรขโมยสินค้า", roledescriptionused: "Individual engaged in the act of stealing merchandise from the supermarket without paying.<br><br>บุคคลที่มีส่วนร่วมในการขโมยสินค้าจากร้านซุปเปอร์มาร์เก็ตโดยไม่จ่ายเงิน" },
    {roleused: "Lost Child", thairoleused: "<br>เด็กที่หลงทาง", roledescriptionused: "A child who got separated from their parent or guardian within the supermarket.<br><br>เด็กที่ได้รับการแยกจากพ่อครัวหรือผู้ปกครองภายในซุปเปอร์มาร์เก็ต" },
    {roleused: "Lost Child's Parent", thairoleused: "<br>ผู้ปกครองเด็กที่หลงทาง", roledescriptionused: "Parent searching for a lost child within the supermarket.<br><br>ผู้ปกครองที่ค้นหาลูกที่หลงทางภายในซุปเปอร์มาร์เก็ต" },
    {roleused: "Coupon Hoarder", thairoleused: "<br>คนที่เก็บคูปองสะสม", roledescriptionused: "Customer who collects and saves a large number of coupons for future use.<br><br>ลูกค้าที่เก็บรวบรวมและเก็บรักษาจำนวนมากของคูปองเพื่อใช้ในอนาคต" },
];

/*25 role*/
const BeachRole = [
    {roleused: "Lifeguard", thairoleused: "<br>นักดูแลชายหาด", roledescriptionused: "Ensures beach safety and responds to emergencies.<br><br>รักษาความปลอดภัยในชายหาดและตอบสนองกรณีฉุกเฉิน"},
    {roleused: "Surfer", thairoleused: "<br>นักโต้คลื่น", roledescriptionused: "Rides ocean waves using surfboards.<br><br>ขี่คลื่นทะเลด้วยบอร์ดเซิร์ฟ"},
    {roleused: "Beach Cleaner", thairoleused: "<br>พนักงานทำความสะอาดชายหาด", roledescriptionused: "Maintains beach cleanliness.<br><br>รักษาความสะอาดชายหาด"},
    {roleused: "Beach Photographer", thairoleused: "<br>ช่างภาพชายหาด", roledescriptionused: "Captures moments at the beach.<br><br>ถ่ายรูปช็อตและฉากต่าง ๆ ที่ชายหาดเพื่อให้บริการถ่ายภาพแก่คนที่มาชายหาด"},
    {roleused: "Beach Vendor", thairoleused: "<br>พ่อค้าแม่ค้าชายหาด", roledescriptionused: "sells products and services on the beach.<br><br>ขายสินค้าและบริการบนชายหาด"},
    {roleused: "Beach Bartender", thairoleused: "<br>บาร์เทนเดอร์ชายหาด", roledescriptionused: "serves drinks at beachside bars.<br><br>ทำงานที่บาร์ติดชายหาดโดยให้บริการเครื่องดื่มและค็อกเทลแก่ผู้มาชายหาด"},
    {roleused: "Beach Volleyballer", thairoleused: "<br>นักเล่นวอลเลย์บอลชายหาด", roledescriptionused: "Participate in beach volleyball matches and tournaments on the sand.<br><br>นักเล่นวอลเลย์บอลชายหาดร่วมงานแข่งวอลเลย์บอลชายหาดและทัวร์นาเมนต์บนทราย"},
    {roleused: "Beach DJ", thairoleused: "<br>ดีเจชายหาด", roledescriptionused: "Provide music and entertainment on the beach, creating a lively atmosphere.<br><br>ให้บริการดนตรีและความบันเทิงบนชายหาดเพื่อสร้างบรรยากาศเต็มไปด้วยความสนุกสนาน"},
    {roleused: "Yoga Instructor", thairoleused: "<br>ครูสอนโยคะชายหาด", roledescriptionused: "Lead yoga sessions on the beach, promoting relaxation and fitness.<br><br>นำเซสชันโยคะบนชายหาดเพื่อส่งเสริมความผ่อนคลายและสุขภาพ"},
    {roleused: "Party Planner", thairoleused: "<br>ผู้วางแผนปาร์ตี้ชายหาด", roledescriptionused: "Organize and manage beach parties and events.<br><br>วางแผนปาร์ตี้ชายหาดจัดการและบริหารงานปาร์ตี้และกิจกรรมบนชายหาด"},
    {roleused: "Beachcomber", thairoleused: "<br>คนเดินชายหาด", roledescriptionused: "Individuals who search for seashells and treasures on the beach.<br><br>ผู้ที่ค้นหาหอยทะเลและของมีค่าต่าง ๆ บนชายหาด"},
    {roleused: "Umbrella Rental", thairoleused: "<br>บริการเช่าร่มชายหาด", roledescriptionused: "Provides the service of renting umbrellas to beachgoers for shade.<br><br>บริการเช่าร่มชายหาดให้คนที่มาชายหาดเพื่อร่มเงา"},
    {roleused: "Rubber Ring Rental", thairoleused: "<br>พนักงานให้เช่าห่วงยาง", roledescriptionused: "Manages the rental of rubber rings, providing beachgoers with a fun and relaxing water activity.<br><br>จัดการเช่าปีนยาง เพื่อให้ผู้ท่องเที่ยวที่มาที่ชายหาดได้เพลิดเพลินกับกิจกรรมน้ำที่สนุกและผ่อนคลาย" },
    {roleused: "Life Vest Rental", thairoleused: "<br>พนักงานให้เช่าเสื้อชูชีพ", roledescriptionused: "Manages the rental of life vests, ensuring the safety of beachgoers engaging in water activities.<br><br>จัดการเช่าเสื้อชูชีพ เพื่อรับรองความปลอดภัยของผู้ท่องเที่ยวที่มีกิจกรรมน้ำ" },
    {roleused: "Resort Manager", thairoleused: "<br>ผู้จัดการรีสอร์ทชายหาด", roledescriptionused: "Oversee the operations and management of beachfront resorts.<br><br>ควบคุมการดำเนินงานประจำวันและประสบการณ์ของแขกในรีสอร์ทริมชายหาด"},
    {roleused: "Beach Dog", thairoleused: "<br>หมาชายหาด", roledescriptionused: "Friendly canine companions enjoying the beach atmosphere. หมาที่มีโอกาสสนุกกับชายหาดและคนๆ รอบข้างในบรรยากาศแห่งการพักผ่อนแบบอิสระบนชายหาด"},
    {roleused: "Bikini Girl", thairoleused: "<br>สาวบิกินี่", roledescriptionused: "Individuals wearing stylish swimwear, adding to the beach vibe.<br><br>ผู้หญิงที่เลือกสวมใส่ชุดว่ายน้ำและพร้อมสนุกกับทะเลและดวงอาทิตย์ที่ชายหาด"},
    {roleused: "Drowning Person", thairoleused: "<br>คนจมน้ำ", roledescriptionused: "Individuals in distress and needing immediate rescue assistance in the water.<br><br>บุคคลที่ต้องการความช่วยเหลือหรือการกู้ชีวิตเมื่อตกลงน้ำในทะเลหรือสระว่ายน้ำ"},
    {roleused: "Shell Collector", thairoleused: "<br>คนสะสมหอย", roledescriptionused: "Enjoys collecting seashells and exploring the shoreline for unique specimens.<br><br>ชอบสะสมหอยทากและสำรวจชายฝั่งเพื่อหาตัวอย่างที่เป็นเอกลักษณ์" },
    {roleused: "Sandcastle Artist", thairoleused: "<br>ศิลปินสร้างประสาททราย", roledescriptionused: "Creates intricate and beautiful sandcastles on the beach for everyone to admire.<br><br>สร้างป้อมทรายที่ซับซ้อนและสวยงามที่ชายหาดเพื่อให้ทุกคนมองชม" },
    {roleused: "Seafisherman", thairoleused: "<br>ชาวประมงทะเล", roledescriptionused: "An experienced fisherman who spends their time catching a variety of fish in the sea.<br><br>ชาวประมงที่มีประสบการณ์ที่ใช้เวลาในการจับปลาต่าง ๆ ในทะเล" },
    {roleused: "Shark", thairoleused: "<br>ปลาฉลาม", roledescriptionused: "A marine animal known for its powerful presence and distinctive appearance.<br><br>สัตว์ทะเลที่มีมานระบบและลักษณะเด่นที่เป็นเอกลักษณ์" },
    {roleused: "Jet Ski Enthusiast", thairoleused: "<br>นักขับจั๊ดสกี", roledescriptionused: "Enjoys riding jet skis on the water, showcasing skills and performing tricks.<br><br>สนุกกับการขับจั๊ดสกีบนน้ำ โชว์ทักษะและทำเทคนิคต่าง ๆ" },
    {roleused: "Lighthouse Keeper", thairoleused: "<br>ผู้เฝ้ารักษาป้อมไฟ", roledescriptionused: "Ensures the safety of coastal navigation by maintaining and operating the beachside lighthouse.<br><br>รักษาความปลอดภัยในการนำทางบริเวณชายฝั่งโดยการดูแลรักษาและทำงานที่ป้อมไฟที่ชายหาด" },
    {roleused: "Treasure Hunter", thairoleused: "<br>นักล่าสมบัติ", roledescriptionused: "Searches for hidden treasures along the shore, creating an air of excitement.<br><br>ค้นหาสมบัติที่ซ่อนอยู่ตามชายฝั่ง สร้างบรรยากาศของความตื่นเต้น" },
];

/*14 role*/
const ChurchRole = [
    {roleused: "Priest", thairoleused: "<br>นักบวช", roledescriptionused: "Spiritual leader who conducts religious ceremonies and provides guidance to the congregation.<br><br>ผู้นำทางธรรมศาสนาที่ทำพิธีศาสนาและให้คำแนะนำแก่ประชากร" },
    {roleused: "Nun", thairoleuse: "<br>นักบวชหญิง", roledescriptionused: "A woman who has taken vows to live a religious and ascetic life, often associated with a particular religious order.<br><br>ผู้หญิงที่ได้รับสัตยาบันทึกที่จะมีชีวิตในทางศาสนาและเป็นการเสริมสร้างความทุกข์ทรมาน บ่อยครั้งมีความเกี่ยวข้องกับอันดับศาสนาที่เฉพาะเจาะจง" },
    {roleused: "Satan", thairoleuse: "<br>ซาตาน", roledescriptionused: "A powerful and malevolent supernatural entity associated with darkness and temptation.<br><br>เป็นกำลังที่มีพลังและปรารถนาชั่วร้ายที่เกี่ยวข้องกับความมืดและการล่อลวง" },
    {roleused: "Jesus", thairoleuse: "<br>พระเยซู", roledescriptionused: "A central figure in Christianity, known for teachings of love, compassion, and spiritual guidance.<br><br>บุคคลสำคัญในคริสต์นิกายที่โดดเด่นด้วยการสอนเรื่องรัก ความเมตตา และการแนะนำทางวิญญาณ" },
    {roleused: "Church Volunteer", thairoleused: "<br>อาสาสมัครในโบสถ์", roledescriptionused: "Dedicated individual contributing time and effort to assist with various church activities.<br><br>บุคคลที่มุ่งมั่นและทุ่มเทในการบริจาคเวลาและพยายามในการช่วยเหลือในกิจกรรมต่าง ๆ ของโบสถ์" },
    {roleused: "Church Historian", thairoleused: "<br>นักประวัติศาสตร์ของโบสถ์", roledescriptionused: "Documents and preserves the historical aspects and events of the church.<br><br>เก็บรักษาและสืบทอดด้านประวัติศาสตร์และเหตุการณ์ของโบสถ์" },
    {roleused: "Bible Study Leader", thairoleused: "<br>ผู้นำการศึกษาคัมภีร์", roledescriptionused: "Leads discussions and studies focused on understanding and interpreting the Bible.<br><br>นำการสนทนาและการศึกษาที่เน้นไปที่การเข้าใจและการตีความคัมภีร์" },
    {roleused: "Sign Language Interpreter", thairoleused: "<br>นักแปลภาษามือ", roledescriptionused: "Interprets church services and events for the hearing-impaired using sign language.<br><br>แปลบริการและกิจกรรมในโบสถ์สำหรับผู้ที่มีสมองพิการทางการได้ยินโดยใช้ภาษามือ" },    
    {roleused: "Sinner", thairoleused: "คนบาป", roledescriptionused: "Embarks on a journey of repentance, seeking forgiveness and spiritual guidance within the church community.<br><br>เริ่มต้นการเดินทางของการกลับคืนตัวโดยมีความตั้งใจที่จะขออภัยและคำแนะนำทางจิตวิญญาณภายในชุมชนโบสถ์" },
    {roleused: "Religious Devotee", thairoleused: "<br>ผู้ที่เคร่งศาสนา", roledescriptionused: "A devout follower deeply committed to the teachings and practices of the church, actively participating in religious ceremonies and events.<br><br>ผู้นำในทางศาสนาที่มุ่งมั่นต่อการสอนและปฏิบัติของโบสถ์ การมีส่วนร่วมอย่างมีเสน่ห์ในพิธีศาสนาและเหตุการณ์ทางศาสนา" },
    {roleused: "Devotee", thairoleused: "<br>ผู้นับถือศรัทธา", roledescriptionused: "A committed follower who actively participates in regular prayer sessions, ceremonies, and community activities within the church.<br><br>ผู้ที่มีความมุ่งมั่นและมีส่วนร่วมอย่างสม่ำเสมอในการสวดมนต์ทุกครั้ง พิธีศาสนาและกิจกรรมทางชุมชนภายในโบสถ์" },
    {roleused: "Elderly", thairoleused: "<br>ผู้สูงอายุ", roledescriptionused: "An esteemed senior member of the church community, bringing a wealth of experience and a comforting presence to fellow congregants.<br><br>สมาชิกผู้สูงอายุที่มีชื่อเสียงในชุมชนโบสถ์ซึ่งนำเสนอประสบการณ์ที่ดีและการมีอยู่ที่สบายใจให้แก่สมาชิกคนอื่น" },
    {roleused: "Church Baker", thairoleused: "<br>พ่อครัวของโบสถ์", roledescriptionused: "Prepares baked goods for church events, contributing to the community's culinary delight.<br><br>เตรียมอาหารเบเกอรีสำหรับกิจกรรมของโบสถ์ มีส่วนร่วมในความยินดีทางทัศนคติของชุมชน" },
    {roleused: "Janitor", thairoleused: "<br>พนักงานทำความสะอาด", roledescriptionused: "Responsible for cleaning and maintaining the cleanliness of the church premises. Works behind the scenes to ensure a tidy and welcoming environment.<br><br>รับผิดชอบในการทำความสะอาดและรักษาความสะอาดของบริเวณโบสถ์ ทำงานที่หลังเวทีเพื่อให้มีสภาพแวดล้อมที่เรียบร้อยและเป็นกันเอง" },
];

/*25 role*/
const ForestRole = [
    {roleused: "Botanist", thairoleused: "<br>นักพฤกษศาสตร์", roledescriptionused: "Studies plants and their ecosystems in the forest, identifying species and analyzing their behavior.<br><br>ศึกษาพืชและระบบนิเวศในป่า การระบุชนิดและการวิเคราะห์พฤหัสฯ" },
    {roleused: "Forest Ranger", thairoleused: "<br>ผู้ดูแลป่า", roledescriptionused: "Protects the forest, monitors wildlife, and ensures the well-being of the ecosystem.<br><br>ป้องกันป่า ตรวจสอบสัตว์ป่าและรักษาสุขภาพของระบบนิเวศ" },
    {roleused: "Mushroom Forager", thairoleused: "<br>คนเก็บเห็ด", roledescriptionused: "Searches for and collects various types of mushrooms in the forest, skilled in identification.<br><br>ค้นหาและเก็บเห็ดต่าง ๆ ในป่า มีทักษะในการระบุ" },
    {roleused: "Fruit Gatherer", thairoleused: "<br>คนเก็บผลไม้", roledescriptionused: "Collects various fruits and berries in the forest, knowledgeable about edible plants.<br><br>เก็บรวบผลไม้และเบอร์รี่ต่าง ๆ ในป่า มีความรู้เกี่ยวกับพืชที่สามารถทานได้" },
    {roleused: "Birdwatcher", thairoleused: "<br>นักดูนก", roledescriptionused: "Observes and identifies bird species in the forest, documenting their behavior and migration patterns.<br><br>สังเกตและระบุชนิดของนกในป่า จดบันทึกพฤติกรรมและแบบแรก" },
    {roleused: "Lumberjack", thairoleused: "<br>คนตัดไม้", roledescriptionused: "Cuts down trees and processes wood in the forest, often working with logging equipment.<br><br>ตัดต้นไม้และประมวลผลไม้ในป่า บ่อยครั้งทำงานกับอุปกรณ์ขุดขจัด" },
    {roleused: "Hermit", thairoleused: "<br>ฤๅษี", roledescriptionused: "Lives a secluded life in the heart of the forest, away from civilization, with deep knowledge of the natural surroundings.<br><br>มีชีวิตอยู่ในที่สงบในกลางป่า ห่างจากชีวิตเมือง มีความรู้ลึกเกี่ยวกับสภาพแวดล้อมธรรมชาติ" },
    {roleused: "Nature Photographer", thairoleused: "<br>ช่างภาพธรรมชาติ", roledescriptionused: "Captures the beauty of the forest through photography, focusing on landscapes, wildlife, and plants.<br><br>บันทึกความงามของป่าผ่านการถ่ายภาพ โฟกัสที่ทัศนียภาพ สัตว์ป่า และพืช" },
    {roleused: "Wildlife Biologist", thairoleused: "<br>นักชีววิทยาสัตว์ป่า", roledescriptionused: "Studies the behavior and ecology of wildlife in the forest, contributing to conservation efforts.<br><br>ศึกษาพฤติกรรมและนิเวศวิทยาของสัตว์ป่า ส่งเสริมงานอนุรักษ์" },
    {roleused: "Forest Guide", thairoleused: "<br>ผู้นำป่า", roledescriptionused: "Leads groups through the forest, providing information about flora, fauna, and safety guidelines.<br><br>นำกลุ่มผ่านป่า ให้ข้อมูลเกี่ยวกับพืชสัตว์ และแนวทางความปลอดภัย" },
    {roleused: "Forest Explorer", thairoleused: "<br>นักสำรวจป่า", roledescriptionused: "Ventures deep into the forest, discovering hidden paths and uncovering the secrets of nature.<br><br>ผจญภัยลึกลงในป่า ค้นพบเส้นทางที่ซ่อนเร้นและเปิดเผยความลับของธรรมชาติ" },
    {roleused: "Forest Spirit", thairoleused: "<br>วิญญาณป่า", roledescriptionused: "A mystical entity that embodies the spirit of the forest, connected to its magic and ancient wisdom.<br><br>ตัวละครที่เป็นฤทธิ์เหล่านี้ที่แสดงถึงจิตวิญญาณของป่า ที่เชื่อมโยงกับเวทมนตร์และปัญญาโบราณของมัน" },
    {roleused: "Arsonist", thairoleused: "<br>นักวางเพลิง", roledescriptionused: "A person who intentionally sets fires with the aim of causing damage or destruction.<br><br>บุคคลที่ตั้งใจจุดไฟเพื่อทำความเสียหายหรือทำลายสิ่งของ" },
    {roleused: "Lost's Person", thairoleused: "<br>คนที่หลงทาง", roledescriptionused: "A person who has become disoriented and separated from the group, needing assistance to find their way back.<br><br>บุคคลที่สับสนและห่างไปจากกลุ่ม ต้องการความช่วยเหลือในการหาทางกลับ" },
    {roleused: "Wild Animals", thairoleused: "<br>สัตว์ป่า", roledescriptionused: "A creature native to the wilderness, living and surviving in its natural habitat. Possesses unique behaviors and characteristics.<br><br>สัตว์ที่มีบริวารแต่เพียงในธรรมชาติ อาศัยและรอดตายในสภาพแวดล้อมธรรมชาติของมัน เป็นเจ้าของพฤติกรรมและลักษณะเฉพาะ" },
    {roleused: "Camper", thairoleused: "<br>นักแคมป์", roledescriptionused: "An individual who enjoys outdoor camping activities, skilled in setting up campsites and surviving in the wilderness.<br><br>บุคคลที่ชื่นชอบกิจกรรมแคมป์กลางธรรมชาติ มีทักษะในการตั้งแคมป์และรอดตายในสภาพแวดล้อมธรรมชาติ" },
    {roleused: "Eco-Activist", thairoleused: "<br>นักกิจกรรมสิ่งแวดล้อม", roledescriptionused: "Passionate about environmental conservation, advocates for protecting the forest and its inhabitants.<br><br>หลงใหลในการอนุรักษ์สิ่งแวดล้อม สนับสนุนในการป้องกันป่าและพวกอาศัย" },
    {roleused: "Herbalist", thairoleused: "<br>นักสมุนไพร", roledescriptionused: "A person with extensive knowledge of forest plants, using herbs for healing and other purposes.<br><br>บุคคลที่มีความรู้ลึกเกี่ยวกับพืชในป่า ใช้สมุนไพรเพื่อการรักษาและวัตถุประสงค์อื่น ๆ" },
    {roleused: "Rock Climber", thairoleused: "<br>นักปีนหินผา", roledescriptionused: "An expert in climbing rock formations in the forest, exploring elevated areas for observation.<br><br>นักปีนที่เชี่ยวชาญในการปีนตามรูปแบบหินในป่า สำรวจพื้นที่สูงเพื่อการสังเกต" },
    {roleused: "Forest Archaeologist", thairoleused: "<br>นักโบราณคดีป่า", roledescriptionused: "Studies historical artifacts and traces of human activity in the forest, uncovering its past.<br><br>ศึกษาโบราณวัตถุและร่องรอยของกิจกรรมมนุษย์ในป่า เปิดเผยประวัติของมัน" },
    {roleused: "Sky Observer", thairoleused: "<br>ผู้สังเกตฟ้า", roledescriptionused: "Focuses on observing celestial bodies and meteorological phenomena in the forest sky.<br><br>เน้นการสังเกตวัตถุทางฟ้าและปรากฏการณ์ทางอุตสาหกรรมอากาศในท้องฟ้าป่า" },
    {roleused: "Backwoodsman", thairoleused: "<br>คนป่า", roledescriptionused: "An individual living in the remote wilderness, skilled in survival and familiar with the secrets of the backcountry.<br><br>บุคคลที่อาศัยอยู่ในทุ่งเสม็ดเปลี่ยนห่างไกล มีทักษะในการรอดตายและคุ้นเคยกับความลับของที่ป่า" },
    {roleused: "Trapper", thairoleused: "<br>นักดักสัตว์", roledescriptionused: "Skilled in setting traps to catch animals, providing resources for survival in the backwoods.<br><br>เชี่ยวชาญในการตั้งกับดักเพื่อจับสัตว์ ให้ทรัพยากรสำหรับการรอดตายในทุ่งเสม็ดเปลี่ยน" },
];

/*25 role*/
const PoliceStationRole = [
  {roleused: "Police Officer", thairoleused: "<br>เจ้าหน้าที่ตำรวจ", roledescriptionused: "Enforces the law, maintains public order, and investigates crimes within the jurisdiction.<br><br>ปฏิบัติตามกฎหมาย รักษาความสงบสุขของสาธารณชน และสืบสวนอาชญากรรมในเขตอำนาจ" },
  {roleused: "Detective", thairoleused: "<br>นักสืบ", roledescriptionused: "Investigates complex cases, gathers evidence, and solves crimes with analytical skills.<br><br>สืบสวนคดีที่ซับซ้อน รวบรวมหลักฐาน และแก้ไขอาชญากรรมด้วยทักษะการวิเคราะห์" },
  {roleused: "Forensic Scientist", thairoleused: "<br>นักนิติวิทยาศาสตร์", roledescriptionused: "Examines crime scene evidence, conducts forensic analysis, and provides scientific insights.<br><br>ตรวจสอบหลักฐานที่สถานที่เกิดเหตุ ดำเนินการวิเคราะห์ทางนิรภัย และให้ข้อคิดทางวิทยาศาสตร์" },
  {roleused: "Patrol Officer", thairoleused: "<br>เจ้าหน้าที่ลาดตระเวน", roledescriptionused: "Maintains visibility in the community, responds to calls, and ensures public safety.<br><br>รักษาความสามารถในชุมชน ตอบสนองต่อการโทรเรียกร้อง และรักษาความปลอดภัยของสาธารณชน" },
  {roleused: "K-9 Handler", thairoleused: "<br>ผู้จัดการสุนัขตรวจสอบ", roledescriptionused: "Handles trained police dogs for various tasks, including tracking and drug detection.<br><br>จัดการสุนัขตำรวจที่ได้รับการฝึกสอนสำหรับงานต่าง ๆ เช่นการติดตามและการค้นหายาเสพติด" },
  {roleused: "Crime Scene Photographer", thairoleused: "<br>ช่างภาพที่สถานที่เกิดเหตุ", roledescriptionused: "Captures detailed photographs of crime scenes, providing visual documentation for investigations.<br><br>บันทึกภาพถ่ายละเอียดของสถานที่เกิดเหตุ เพื่อให้เป็นเอกสารทางสายตาสำหรับการสืบสวน" },
  {roleused: "Traffic Cop", thairoleused: "<br>ตำรวจจราจร", roledescriptionused: "Monitors and enforces traffic laws, ensuring the safe flow of vehicles on the roads.<br><br>ตรวจสอบและปฏิบัติตามกฎหมายจราจร เพื่อรักษาการไหลของยานพาหนะในทาง" },
  {roleused: "Criminal Profiler", thairoleused: "<br>นักวิเคราะห์ลักษณะอาชญากร", roledescriptionused: "Analyzes criminal behavior and provides insights into the motivations and characteristics of offenders.<br><br>วิเคราะห์พฤติกรรมของอาชญากร และให้ความรู้เกี่ยวกับแรงจูงใจและลักษณะของผู้กระทำผิด" },
  {roleused: "Evidence Custodian", thairoleused: "<br>ผู้เก็บรักษาหลักฐาน", roledescriptionused: "Manages and preserves physical evidence collected during investigations, ensuring its integrity.<br><br>จัดการและรักษาหลักฐานทางกายที่เก็บรวมในระหว่างการสืบสวน เพื่อให้มั่นใจถึงความสมบูรณ์" },
  {roleused: "Cold Case Detective", thairoleused: "<br>นักสืบคดีเก่า", roledescriptionused: "Specializes in re-examining unsolved cases, applying new techniques and technology.<br><br>เชี่ยวชาญในการสำรวจคดีที่ยังไม่ได้แก้ไข ใช้เทคนิคและเทคโนโลยีใหม่" },
  {roleused: "Cyber Police", thairoleused: "<br>ตํารวจทางไซเบอร์", roledescriptionused: "An officer specialized in investigating and combating cybercrimes, ensuring digital security.<br><br>เจ้าหน้าที่ที่เชี่ยวชาญในการสืบสวนและต่อต้านอาชญากรรมทางไซเบอร์ รับผิดชอบในการรักษาความปลอดภัยทางดิจิทัล" },
  {roleused: "Victim", thairoleused: "<br>เหยื่อ", roledescriptionused: "An unfortunate individual who has fallen victim to a crime, providing crucial information to investigators.<br><br>บุคคลที่ไม่มีโชคลาภที่ตกเป็นเหยื่อของอาชญากรรม ให้ข้อมูลสำคัญให้กับผู้สืบสวน" },
  {roleused: "Criminal", thairoleused: "<br>อาชญากร", roledescriptionused: "A person involved in unlawful activities, possibly being investigated by the police.<br><br>บุคคลที่มีส่วนเกี่ยวข้องกับกิจกรรมที่ผิดกฎหมาย อาจถูกสืบสวนโดยตำรวจ" },
  {roleused: "Temporary Prisoner", thairoleused: "<br>นักโทษชั่วคราว", roledescriptionused: "An individual detained temporarily, awaiting legal processes or questioning by authorities.<br><br>บุคคลที่ถูกกักขังชั่วคราว รอการดำเนินคดีทางกฎหมายหรือการถามคำถามจากเจ้าหน้าที่" },
  {roleused: "Warden", thairoleused: "<br>ผู้คุมขัง", roledescriptionused: "Oversees the management and security of the jail facility, ensuring order among detainees.<br><br>ควบคุมการจัดการและรักษาความปลอดภัยในสถานที่เก็บกักของ เพื่อรักษาความเรียบร้อยในหมู่ผู้ต้องขัง" },
  {roleused: "Police Trainee", thairoleused: "<br>ตำรวจฝึกสอน", roledescriptionused: "Learning the ropes and gaining practical experience under the guidance of seasoned officers.<br><br>กำลังเรียนรู้พื้นฐานและได้รับประสบการณ์จริงภายใต้การแนะนำของเจ้าหน้าที่ที่มีประสบการณ์" },
  {roleused: "Desk Police", thairoleused: "<br>ตำรวจด่านตรวจ", roledescriptionused: "Supervises the front desk, assigns tasks, and coordinates communication within the station.<br><br>ควบคุมด่านตรวจ มอบหมายงาน และประสานสื่อในสถานี" },
  {roleused: "Lost's Child", thairoleused: "<br>เด็กหาย", roledescriptionused: "A scared child separated from their parent in a crowded place, seeking help to find them.<br><br>เด็กที่กลัวที่ได้รับแยกจากพ่อแม่ในที่คนเยอะ ต้องการความช่วยเหลือในการค้นหา" },
  {roleused: "911 Communicator", thairoleused: "<br>ผู้ติดต่อสายฉุกเฉิน 911", roledescriptionused: "Handles emergency calls, gathers information, and dispatches appropriate help to the location.<br><br>จัดการสายฉุกเฉิน 911 รวบรวมข้อมูลและส่งความช่วยเหลือที่เหมาะสมไปยังที่เกิดเหตุ" },
  {roleused: "Drone Operator", thairoleused: "<br>ผู้ดำเนินการโดรนตำรวจ", roledescriptionused: "Operates drones for aerial surveillance, search and rescue missions, and traffic monitoring.<br><br>ดำเนินการโดรนเพื่อการสอบสวนทางอากาศ ภารกิจค้นหาและกู้ภัย และการติดตามจราจร" },
  {roleused: "K-9 Dog", thairoleused: "<br>สุนัขตำรวจ K-9", roledescriptionused: "A highly trained police dog specializing in tasks such as tracking, search, and apprehension.<br><br>สุนัขตำรวจที่ได้รับการฝึกฝนอย่างมีความสามารถ เชี่ยวชาญในงานต่าง ๆ เช่นการติดตาม ค้นหา และกล่าวยึด" },
  {roleused: "Helicopter Pilot", thairoleused: "<br>นักบินเฮลิคอปเตอร์", roledescriptionused: "Operates a helicopter for aerial surveillance, pursuit, and assistance in various operations.<br><br>ดำเนินการเฮลิคอปเตอร์เพื่อการสอบสวนทางอากาศ การตามล่า และการช่วยเหลือในงานต่าง ๆ" },
  {roleused: "Inspector", thairoleused: "<br>สารวัตร", roledescriptionused: "Oversees and manages investigations, ensuring thorough examination of cases and adherence to procedures.<br><br>ควบคุมและจัดการการสืบสวน เพื่อให้การตรวจสอบของเคสเป็นอย่างละเอียดและเชื่อมั่นในการปฏิบัติตามขั้นตอน" },
  {roleused: "Reporter", thairoleused: "<br>ผู้สื่อข่าว", roledescriptionused: "Covers and reports on news related to the police department, investigations, and crime events.<br><br>รายงานข่าวเกี่ยวกับกองตำรวจ การสืบสวน และเหตุการณ์อาชญากรรม" },
  {roleused: "Victim's Family", thairoleused: "<br>ครอบครัวของเหยื่อ", roledescriptionused: "The family members of a crime victim, providing emotional support and cooperation with authorities.<br><br>สมาชิกในครอบครัวของเหยื่ออาชญากรรม ให้การสนับสนุนทางอารมณ์และร่วมมือกับเจ้าหน้าที่" },
];

/*25 role*/
const PirateShipRole = [
  {roleused: "Captain", thairoleused: "<br>กัปตัน", roledescriptionused: "The leader of the pirate crew, making decisions and steering the ship.<br><br>ผู้นำกลุ่มโจรสลัด ตัดสินใจและทำให้เรือไปตามทิศทางที่ต้องการ" },
  {roleused: "Treasure Map Maker", thairoleused: "<br>ผู้ทำแผนที่สมบัติ", roledescriptionused: "Crafts maps leading to hidden treasures and navigates the crew to find them.<br><br>สร้างแผนที่ที่นำไปสู่สมบัติที่ซ่อนอยู่และนำทีมไปค้นหา" },
  {roleused: "Navigator", thairoleused: "<br>ต้นหน", roledescriptionused: "Charts the course, ensuring the ship reaches its intended destinations.<br><br>วาดแผนที่เส้นทางเพื่อให้เรือไปถึงที่ปลายทางที่ตั้งไว้" },
  {roleused: "Ship's Gunner", thairoleused: "<br>คนปืนเรือ", roledescriptionused: "Handles and operates the ship's cannons and firearms during battles.<br><br>ดูแลและใช้ปืนใหญ่และอาวุธปืนของเรือในระหว่างการต่อสู้" },
  {roleused: "Lookout", thairoleused: "<br>ผู้คอยดู", roledescriptionused: "Keeps a watchful eye for potential threats and other ships on the horizon.<br><br>ตรวจสอบสิ่งที่อาจเป็นอันตรายและเรืออื่น ๆ ที่อาจปรากฏบนขอบฟ้า" },
  {roleused: "Cook", thairoleused: "<br>หัวห้องครัว", roledescriptionused: "Prepares meals for the crew, utilizing limited resources on the ship.<br><br>เตรียมอาหารสำหรับลูกเรือ โดยใช้ทรัพยากรจำกัดบนเรือ" },
  {roleused: "Cabin Boy/Girl", thairoleused: "<br>เด็กในกระโจม", roledescriptionused: "Young crew member who assists with various tasks and chores on the ship.<br><br>สมาชิกทีมที่เป็นเด็กที่ช่วยเหลือในหลายงานและหน้าที่บนเรือ" },
  {roleused: "Bosun", thairoleused: "<br>คนบูรณะเรือ", roledescriptionused: "Oversees the maintenance and repair of the ship, ensuring it stays seaworthy.<br><br>ควบคุมการบำรุงรักษาและซ่อมแซมเรือ เพื่อให้รักษาสภาพพร้อมใช้ในทะเล" },
  {roleused: "Sailmaker", thairoleused: "<br>ช่างทำเรือยอรา", roledescriptionused: "Repairs and maintains the ship's sails to optimize wind capture.<br><br>ซ่อมแซมและดูแลรักษาใบเรือเพื่อให้ได้ประสิทธิภาพในการจับลม" },
  {roleused: "Island Cartographer", thairoleused: "<br>ผู้ทำแผนที่เกาะ", roledescriptionused: "Creates detailed maps of islands and coastal areas explored by the pirate crew.<br><br>สร้างแผนที่ละเอียดของเกาะและพื้นที่ชายฝั่งที่ได้รับการสำรวจจากกลุ่มโจรสลัด" },
  {roleused: "Mermaid/Merman", thairoleused: "<br>นางเงือก/นายเงือก", roledescriptionused: "A mythical sea creature that may befriend or deceive the pirate crew.<br><br>สัตว์ทะเลที่แต่งตัวในนิทานที่อาจเป็นเพื่อนหรือหลอกลวงกลุ่มโจรสลัด" },
  {roleused: "Sunken Treasure Diver", thairoleused: "<br>นักดำน้ำตามหาขุมทรัพย์ที่จม", roledescriptionused: "Specializes in diving to retrieve treasures from sunken ships or hidden locations.<br><br>เชี่ยวชาญในการดำน้ำเพื่อเก็บของพวกของเรือที่จมหรือที่อยู่ที่ซ่อนเร้น" },
  {roleused: "Fortune Teller", thairoleused: "<br>นักทำนายดวง", roledescriptionused: "Possesses mystical abilities to predict the future and provide guidance to the pirate crew.<br><br>มีความสามารถทางเวทมนตร์ในการทำนายอนาคตและให้คำแนะนำในทีมโจรสลัด" },
  {roleused: "Deckhand", thairoleused: "<br>คนทำงานเรือ", roledescriptionused: "Performs various tasks on the ship, assisting in navigation, maintenance, and more.<br><br>ปฏิบัติหน้าที่ต่าง ๆ บนเรือ ช่วยเหลือในการนำทาง การบำรุงรักษา และอื่น ๆ" },
  {roleused: "Kraken", thairoleused: "<br>คราเคน", roledescriptionused: "A legendary sea monster with massive tentacles, lurking in the depths to challenge the pirate crew.<br><br>สัตว์ประหลาดทะเลตำนานที่มีหนวดขนาดใหญ่ ตกอยู่ในทะเลเพื่อท้าทายกับลูกเรือโจรสลัด" },
  {roleused: "Harpoon Thrower", thairoleused: "<br>ผู้โยนฉมวก", roledescriptionused: "Skilled in using harpoons for hunting sea creatures or defending against threats.<br><br>เชี่ยวชาญในการใช้คานในการล่าสัตว์ทะเลหรือป้องกันตนเอง" },
  {roleused: "Shipwright", thairoleused: "<br>ช่างเรือ", roledescriptionused: "Repairs and maintains the ship's structure and components, ensuring seaworthiness.<br><br>ซ่อมแซมและดูแลรักษาโครงสร้างและส่วนประกอบของเรือ เพื่อให้รักษาสภาพพร้อมใช้ในทะเล" },
  {roleused: "Hostage", thairoleused: "<br>ตัวประกัน", roledescriptionused: "A person held captive by pirates, often used as leverage in negotiations.<br><br>บุคคลที่ถูกลักพาตัวโดยโจรสลัด มักถูกใช้เป็นอีกทางในการเจรจาต่อรอง" },
  {roleused: "Parrot", thairoleused: "<br>นกแก้ว", roledescriptionused: "A colorful and talkative companion of the pirate crew, providing entertainment and company.<br><br>เป็นเพื่อนที่สีสันและพูดจาของลูกเรือโจรสลัด ให้ความบันเทิงและเป็นเพื่อนร่วมทาง" },
  {roleused: "Quartermaster", thairoleused: "<br>ผู้จัดการพัสดุ", roledescriptionused: "Responsible for managing and distributing supplies, equipment, and provisions on the pirate ship.<br><br>รับผิดชอบในการจัดการและแจกจ่ายพัสดุ เครื่องมือ และวัสดุบนเรือโจรสลัด" },
  {roleused: "Helmsman", thairoleused: "<br>คนขับเรือ", roledescriptionused: "Steers and navigates the pirate ship, ensuring it follows the desired course and avoids obstacles.<br><br>นำเรือโจรสลัดและนำทางเพื่อให้เรือเดินตามเส้นทางที่ต้องการและหลีกเลี่ยงอุปสรรค" },
  {roleused: "Craftsman", thairoleused: "<br>ช่างฝีมือ", roledescriptionused: "Skilled in creating and repairing various items, from ship components to personal belongings of the crew.<br><br>เชี่ยวชาญในการสร้างและซ่อมแซมของต่าง ๆ ตั้งแต่ส่วนประกอบของเรือถึงของส่วนตัวของลูกเรือ" },
  {roleused: "Musician", thairoleused: "<br>นักดนตรี", roledescriptionused: "Entertains the pirate crew with music, boosting morale and creating a lively atmosphere on the ship.<br><br>บันเทิงลูกเรือโจรสลัดด้วยเสียงเพลง เพื่อเสริมใจและสร้างบรรยากาศมีชีวิตชีวาบนเรือ" },
  {roleused: "Ship's Surgeon", thairoleused: "<br>แพทย์ของเรือ", roledescriptionused: "Provides medical care and attends to the health of the pirate crew during voyages.<br><br>ให้การดูแลทางการแพทย์และดูแลสุขภาพของลูกเรือโจรสลัดในระหว่างการเดินทาง" },
  {roleused: "Scavenger", thairoleused: "<br>นักล่าของหายาก", roledescriptionused: "Searches for valuable items or resources during shore excursions or exploration.<br><br>ค้นหาของมีค่าหรือทรัพยากรในระหว่างการไปที่ฝั่งหรือการสำรวจ" },
];

/*18 role*/
const SubmarineRole = [
  {roleused: "Captain", thairoleused: "<br>กัปตัน", roledescriptionused: "The leader and commander of the submarine crew, responsible for making critical decisions during missions.<br><br>ผู้นำและผู้บังคับบัญชาของลูกเรือใต้ท้องทะเล รับผิดชอบในการตัดสินใจที่สำคัญในระหว่างภารกิจ" },
  {roleused: "Navigator", thairoleused: "<br>นำทาง", roledescriptionused: "Charts the course and navigates the submarine to its destination, avoiding obstacles and dangers.<br><br>กำหนดเส้นทางและนำทางเรือใต้ท้องทะเลไปยังจุดหมาย หลีกเลี่ยงอุปสรรคและอันตราย" },
  {roleused: "Sonar Operator", thairoleused: "<br>ผู้ประสานเสียงลำโพง", roledescriptionused: "Monitors sonar systems to detect underwater objects, submarines, or potential threats.<br><br>ตรวจสอบระบบลำโพงเพื่อตรวจจับวัตถุใต้น้ำ เรือใต้ท้องทะเล หรือความเสี่ยงที่เป็นไปได้" },
  {roleused: "Torpedo Specialist", thairoleused: "<br>ผู้เชี่ยวชาญทอร์ปีโด", roledescriptionused: "Handles the deployment and maintenance of torpedoes, the primary weapon of the submarine.<br><br>ดูแลการจัดตั้งและการบำรุงรักษาทอร์เปโด เป็นอาวุธหลักของเรือใต้ท้องทะเล" },
  {roleused: "Communications Officer", thairoleused: "<br>เจ้าหน้าที่สื่อสาร", roledescriptionused: "Manages communication systems and relays information between the submarine and other units.<br><br>จัดการระบบสื่อสารและส่งข้อมูลระหว่างเรือใต้ท้องทะเลกับหน่วยอื่น ๆ" },
  {roleused: "Diver", thairoleused: "<br>นักดำน้ำ", roledescriptionused: "Conducts underwater missions, repairs, and inspections outside the submarine.<br><br>ดำเนินภารกิจใต้น้ำ ซ่อมแซม และตรวจสอบนอกเรือใต้ท้องทะเล" },
  {roleused: "Hydrographer", thairoleused: "<br>นักทำแผนที่ทางทะเล", roledescriptionused: "Studies and maps the ocean floor, underwater terrain, and currents for navigation purposes.<br><br>ศึกษาและทำแผนที่สำรวจพื้นที่ใต้น้ำ ท้องทะเล และกระแสน้ำเพื่อใช้ในการนำทาง" },
  {roleused: "Submarine Mechanic", thairoleused: "<br>ช่างเครื่องใต้ท้องทะเล", roledescriptionused: "Handles repairs and maintenance of the submarine's mechanical systems and equipment.<br><br>ดูแลการซ่อมแซมและบำรุงรักษาระบบกลไฟและเครื่องจักรของเรือใต้ท้องทะเล" },
  {roleused: "Medical Officer", thairoleused: "<br>เจ้าหน้าที่การแพทย์", roledescriptionused: "Provides medical care for the submarine crew and addresses health concerns during missions.<br><br>ให้การดูแลทางการแพทย์และแก้ไขปัญหาสุขภาพของลูกเรือในระหว่างภารกิจ" },
  {roleused: "Nature Scientist", thairoleused: "<br>นักวิทยาศาสตร์สิ่งแวดล้อม", roledescriptionused: "Studies the underwater environment and its impact on marine life, providing valuable data.<br><br>ศึกษาสิ่งแวดล้อมใต้น้ำและผลกระทบต่อชีวิตในทะเล เพื่อให้ข้อมูลมีค่า" },
  {roleused: "Oceanographer", thairoleused: "<br>นักวิทยาธรณีวิทยาทะเล", roledescriptionused: "Studies the physical and chemical properties of the ocean, providing insights into underwater ecosystems.<br><br>ศึกษาคุณสมบัติทางกายภาพและเคมีของมหาสมุทร เพื่อให้ความรู้เกี่ยวกับระบบนิเวศใต้น้ำ" },
  {roleused: "Submarine Chef", thairoleused: "<br>พ่อครัวเรือดำน้ำ", roledescriptionused: "Prepares meals for the submarine crew, adapting to the challenges of underwater cooking.<br><br>เตรียมอาหารสำหรับลูกเรือดาบดำน้ำ โดยปรับตัวให้เข้ากับความท้าทายของการทำอาหารใต้น้ำ" },
  {roleused: "Angler Fish", thairoleused: "<br>ปลาแองเกิ้ล", roledescriptionused: "Known for its bioluminescent lure, this deep-sea predator attracts prey in the dark depths.<br><br>มีลูกรับแสงที่เปล่งประกายทางชีวภาพ เป็นนักล่าใต้น้ำลึกที่ดึงดูดเหยื่อในความมืดของลึกลงไป" },
  {roleused: "Deep Sea Fish", thairoleused: "<br>ปลาทะเลลึก", roledescriptionused: "A unique and mysterious creature adapted to survive in the extreme conditions of the deep sea.<br><br>สัตว์ที่ไม่ซ้ำกันและลึกลับ ปรับตัวให้สามารถอยู่รอดในสภาพแวดล้อมที่สุดของทะเลลึก" },
  {roleused: "Coelacanth", thairoleused: "<br>ซีลาแคนท์", roledescriptionused: "A prehistoric fish species believed to be extinct but discovered alive in deep-sea environments.<br><br>ชนิดปลาโบราณที่ถือว่าสูญพันธุ์แต่พบมีชีวิตในสภาพแวดล้อมทะเลลึก" },
  {roleused: "Giant Isopod", thairoleused: "<br>ไอโซพอดยักษ์", roledescriptionused: "A deep-sea crustacean with a distinct, segmented exoskeleton, known for its scavenging behavior on the ocean floor.<br><br>สัตว์กระเป๋าทะเลที่มีกระดูกหลังแบ่งเป็นส่วนๆ มีชื่อเสียงในการค้นหาของต่างๆ ที่อยู่บนท้องทะเล" },
  {roleused: "Blobfish", thairoleused: "<br>ปลาบล็อบ", roledescriptionused: "A deep-sea fish with a unique appearance, often appearing gelatinous due to its adaptation to high-pressure environments.<br><br>ปลาทะเลลึกที่มีลักษณะเฉพาะ มักแสดงให้เห็นถึงความหนืดเนื้อเพราะปรับตัวให้ทนต่อแรงดันสูงในสภาพแวดล้อมทะเลลึก" },
  {roleused: "Titanic Ghost", thairoleused: "<br>ผีไททานิค", roledescriptionused: "The lingering spirit of the Titanic, haunting the depths of the ocean as a ghostly presence.<br><br>จิตวิญญาณที่ยังคงอยู่ของไททานิค ปรากฏตัวในความมืดของมหาสมุทรในรูปของผี" },
  {roleused: "Navy", thairoleused: "<br>ทหารเรือ", roledescriptionused: "A member of the naval forces responsible for maritime defense and operations at sea.<br><br>เป็นสมาชิกของกองทัพเรือที่รับผิดชอบในการป้องกันทางทะเลและดำเนินการในทะเล" },
];

/*16 role*/
const RestaurantRole = [
  {roleused: "Head Chef", thairoleused: "<br>เชฟหลัก", roledescriptionused: "Leads the kitchen, responsible for menu planning and overall culinary excellence.<br><br>นำทีมในครัว รับผิดชอบการวางแผนเมนูและคุณภาพอาหารทั่วไป"},
  {roleused: "Waiter/Waitress", thairoleused: "<br>พนักงานเสิร์ฟ", roledescriptionused: "Takes orders, serves food, and ensures guests have a delightful dining experience.<br><br>รับออร์เดอร์ นำเสิร์ฟอาหาร และดูแลประสบการณ์รับประทานอาหารของลูกค้า" },
  {roleused: "Host/Hostess", thairoleused: "<br>เจ้าภาพ/เจ้าภาพี", roledescriptionused: "Greets and seats guests, manages reservations, and ensures a welcoming atmosphere.<br><br>ต้อนรับและนั่งลูกค้า จัดการการจองที่นั่ง และรักษาบรรยากาศที่เป็นกันเอง" },
  {roleused: "Dishwasher", thairoleused: "<br>พนักงานล้างจาน", roledescriptionused: "Cleans and sanitizes dishes, utensils, and kitchen equipment to maintain hygiene.<br><br>ทำความสะอาดและฆ่าเชื้อจาน อุปกรณ์ในครัวเพื่อรักษาความสะอาด" },
  {roleused: "Bartender", thairoleused: "<br>บาร์เทนเดอร์", roledescriptionused: "Mixes and serves beverages, often specializing in cocktails and other drinks.<br><br>ผสมและบริการเครื่องดื่ม โดยมักเชี่ยวชาญในการทำค็อกเทลและเครื่องดื่มอื่นๆ"},
  {roleused: "Barista", thairoleused: "<br>บาริสต้า", roledescriptionused: "Expert in preparing and serving a variety of coffee-based beverages with precision.<br><br>เชี่ยวชาญในการเตรียมและบริการเครื่องดื่มที่มีกาแฟในหลายรูปแบบอย่างพิถีพิถัน" },
  {roleused: "Greeter", thairoleused: "<br>พนักงานต้อนรับ", roledescriptionused: "Welcomes guests with a warm greeting, manages reservations, and directs them to their tables.<br><br>ต้อนรับลูกค้าด้วยทักทายอบอุ่น จัดการการจองที่นั่งและแนะนำไปที่โต๊ะของพวกเขา" },
  {roleused: "Cashier", thairoleused: "<br>พนักงานเก็บเงิน", roledescriptionused: "Handles customer payments, provides receipts, and ensures accurate transactions.<br><br>จัดการการชำระเงินของลูกค้า ออกใบเสร็จ และให้การทำธุรกรรมที่ถูกต้อง" },
  {roleused: "Live Musician", thairoleused: "<br>นักดนตรีแสดงสด", roledescriptionused: "Entertains guests with live music performances, enhancing the ambiance.<br><br>บรรเลงดนตรีสดเพื่อสร้างบรรยากาศที่น่าสนใจในร้าน" },
  {roleused: "Food Critic", thairoleused: "<br>นักวิจารณ์อาหาร", roledescriptionused: "Evaluates and provides reviews on the quality of food and dining experiences.<br><br>ประเมินและให้ความคิดเห็นเกี่ยวกับคุณภาพอาหารและประสบการณ์การรับประทาน" },
  {roleused: "Customer", thairoleused: "<br>ลูกค้า", roledescriptionused: "Enjoys a delightful dining experience, making choices from the restaurant's menu.<br><br>เพลิดเพลินในประสบการณ์รับประทานอาหารที่ยอดเยี่ยม ทำการเลือกรายการจากเมนูของร้าน" },
  {roleused: "Regular Patron", thairoleused: "<br>ลูกค้าประจำ", roledescriptionused: "Frequent visitor who enjoys the familiar atmosphere and menu items of the restaurant.<br><br>ผู้เยี่ยมชมบ่อย ที่ชื่นชอบบรรยากาศที่คุ้นเคยและรายการเมนู" },
  {roleused: "Dissatisfied Customer", thairoleused: "<br>ลูกค้าที่ไม่พอใจ", roledescriptionused: "Experiences dissatisfaction with the dining service or menu choices, seeking resolution.<br><br>มีความไม่พอใจต่อการบริการหรือเมนูอาหาร และมีความต้องการให้มีการแก้ไข" },
  {roleused: "Glutton", thairoleused: "<br>คนตะกละ", roledescriptionused: "Has an insatiable appetite and delights in consuming large quantities of food.<br><br>มีความกระหายนริสนิยมและชอบรับประทานอาหารปริมาณมาก" },
  {roleused: "Vegetarian", thairoleused: "<br>มังสวิรัติ", roledescriptionused: "Prefers a diet that consists primarily of plant-based foods and avoids meat.<br><br>ชอบรับประทานอาหารที่ประกอบไปด้วยพืชและหลีกเลี่ยงเนื้อสัตว์" },
  {roleused: "Drunk Person", thairoleused: "<br>คนเมา", roledescriptionused: "Under the influence of alcohol, exhibiting impaired coordination and judgment.<br><br>อยู่ภายใต้ผลกระทบของแอลกอฮอล์ แสดงอาการขาดสมดุลและการวินิจฉัยที่ลดลง" },
];

/*14 role*/
const CemeteryRole = [
  { roleused: "Grave Digger", thairoleused: "<br>คนขุดหลุมฝังศพ", roledescriptionused: "Excavates graves in cemeteries for burials, following proper procedures and respecting cultural practices.<br><br>ขุดหลุมฝังศพในสุสานตามขั้นตอนที่ถูกต้องและให้เคารพต่อประการศาสตร์" },
  { roleused: "Caretaker", thairoleused: "<br>ผู้ดูแลสุสาน", roledescriptionused: "Maintains the cleanliness and orderliness of the cemetery, ensuring a respectful environment.<br><br>รักษาความสะอาดและเรียบร้อยของสุสาน เพื่อรักษาสภาพแวดล้อมที่เคารพ" },
  { roleused: "Funeral Director", thairoleused: "<br>ผู้จัดการงานศพ", roledescriptionused: "Coordinates and oversees funeral services, providing support to grieving families.<br><br>ประสานงานและควบคุมการให้บริการงานศพ เพื่อให้การสนับสนุนแก่ครอบครัวที่อยู่ในช่วงทุกข์" },
  { roleused: "Gravestone Engraver", thairoleused: "<br>ช่างแกะสลักหลุมฝังศพ", roledescriptionused: "Engraves inscriptions and designs on gravestones with precision and artistry.<br><br>แกะสลักคำลงบนหลุมฝังศพด้วยความแม่นยำและศิลปะ" },
  { roleused: "Chaplain", thairoleused: "<br>นักบวช", roledescriptionused: "Provides spiritual support and conducts religious ceremonies in the cemetery.<br><br>ให้การสนับสนุนทางจิตวิญญาณและปฏิบัติพิธีทางศาสนาในสุสาน" },
  { roleused: "Visitor", thairoleused: "<br>คนมาเยี่ยม", roledescriptionused: "Pays respects, observes, or attends events in the cemetery, participating in memorial activities.<br><br>เคารพไถ่ถาม สังเกตหรือเข้าร่วมกิจกรรมในสุสาน เพื่อร่วมสนับสนุนกิจกรรมที่เกี่ยวกับการระลึกถึงผู้ล่วงลับ" },
  { roleused: "Corpse", thairoleused: "<br>ศพ", roledescriptionused: "Deceased individual whose body is prepared for burial or cremation within the cemetery.<br><br>บุคคลที่เสียชีวิตซึ่งร่างกายได้รับการเตรียมพร้อมสำหรับการฝังศพหรือการเผาศพภายในสุสาน" },
  { roleused: "Corpse Relative", thairoleused: "<br>ญาติของผู้เสียชีวิต", roledescriptionused: "Family member or relative of the deceased individual, participating in funeral and memorial activities.<br><br>สมาชิกครอบครัวหรือญาติของบุคคลที่เสียชีวิต ที่เข้าร่วมในพิธีศพและกิจกรรมระลึกถึงผู้ล่วงลับ" },
  { roleused: "Ghost", thairoleused: "<br>ผี", roledescriptionused: "Spirit or apparition of a deceased individual, believed to linger in the cemetery or specific locations.<br><br>วิญญาณหรือร่างของบุคคลที่เสียชีวิตที่เชื่อว่ายังคงอยู่ในสุสานหรือสถานที่เฉพาะ" },
  { roleused: "Raven", thairoleused: "<br>อีกาดำ", roledescriptionused: "Intelligent bird often associated with mysticism and folklore, residing within the cemetery.<br><br>นกฉลาดที่มักเชื่อมโยงกับความเสน่ห์และประเพณีชาวบ้าน อาศัยอยู่ภายในสุสาน" },
  { roleused: "Coffin Maker", thairoleused: "<br>ช่างทำโลง", roledescriptionused: "Skilled artisan who crafts coffins and caskets for burials within the cemetery.<br><br>ช่างฝีมือที่เชี่ยวชาญที่สร้างโลงและหีบสำหรับการฝังศพในสุสาน" },
  { roleused: "Grave Robber", thairoleused: "<br>คนลักลอบขุดศพ", roledescriptionused: "Individuals who engage in unauthorized digging of graves with the intent of stealing valuables or artifacts.<br><br>บุคคลที่มีส่วนร่วมในการขุดศพโดยไม่ได้รับอนุญาตและมีจุดประสงค์ในการขโมยของมีค่าหรือโบราณวัตถุ" },
  { roleused: "Undertaker", thairoleused: "<br>สัปเหร่อ", roledescriptionused: "Professionals who prepare deceased bodies for burial or cremation, and assist in organizing funeral services.<br><br>ผู้เชี่ยวชาญที่เตรียมร่างศพของผู้เสียชีวิตเพื่อการฝังศพหรือการเผาศพและช่วยในการจัดการบริการศพ" },
  { roleused: "Corpse Makeup Artist", thairoleused: "<br>ช่างแต่งหน้าศพ", roledescriptionused: "Professionals who specialize in applying makeup to deceased individuals, enhancing their appearance for funerals or viewings.<br><br>ผู้เชี่ยวชาญที่มีความเชี่ยวชาญในการแต่งหน้าให้กับบุคคลที่เสียชีวิต เพื่อเพิ่มเติมความงดงามในงานศพหรือการชมไหว้" }
];
const WarfieldRole = []
const AirplaneRole = []
const LibraryRole = []
const StadiumRole = []
const ZooRole = []
const SubwayRole = []
const DocksRole = []
const ArcadeRole = []
const CircusTentRole = []
const GymRole = []
const DungeonRole = []
const DesertRole = []
